font=IosevkaTerm Nerd Font 14
background-color=#06181e
text-color=#dffaff
border-size=4
border-radius=0
progress-color=source #2fc4b2

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#2fc4b2

[urgency=low]
border-color=#39c5ff

[urgency=high]
border-color=#ff6b6b
background-color=#ff6b6b
text-color=#06181e
default-timeout=0
