font=IosevkaTerm Nerd Font 14
background-color=#161616
text-color=#D6D2C8
border-size=3
border-radius=0
progress-color=source #FF5A1F

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#FF5A1F

[urgency=low]
border-color=#6FA39B

[urgency=high]
border-color=#E5533A
background-color=#E5533A
text-color=#161616
default-timeout=0
