font=IosevkaTerm Nerd Font 14
background-color=#232a2e
text-color=#d3c6aa
border-size=4
border-radius=0
progress-color=source #a7c080

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#a7c080

[urgency=low]
border-color=#7fbbb3

[urgency=high]
border-color=#e67e80
background-color=#e67e80
text-color=#232a2e
default-timeout=0
