# Mako: tema matrix

font=IosevkaTerm Nerd Font 14
background-color=#000000
text-color=#c8ffd0
border-size=4
border-radius=0
progress-color=source #00ff41

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#00ff41

[urgency=low]
border-color=#00ff41

[urgency=high]
border-color=#ff3131
background-color=#ff3131
text-color=#000000
default-timeout=0
