# Mako: tema mystbloom

font=IosevkaTerm Nerd Font 14
background-color=#141416
text-color=#eeeeee
border-size=2
border-radius=0
progress-color=source #cda2d4

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#cda2d4

[urgency=low]
border-color=#8a9ca0

[urgency=high]
border-color=#a3697d
background-color=#a3697d
text-color=#141416
default-timeout=0
