# Mako: tema oh-lucy

font=IosevkaTerm Nerd Font 14
background-color=#1B1D26
text-color=#D7D7D7
border-size=2
border-radius=0
progress-color=source #BBBBBB

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#BBBBBB

[urgency=low]
border-color=#6CAEC0

[urgency=high]
border-color=#FB7DA7
background-color=#FB7DA7
text-color=#1B1D26
default-timeout=0
