# Mako: tema poimandres

font=IosevkaTerm Nerd Font 14
background-color=#171922
text-color=#E4F0FB
border-size=2
border-radius=8
progress-color=source #5DE4C7

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#5DE4C7

[urgency=low]
border-color=#89DDFF

[urgency=high]
border-color=#D0679D
background-color=#D0679D
text-color=#171922
default-timeout=0
