# Mako: tema rosepine

font=IosevkaTerm Nerd Font 14
background-color=#191724
text-color=#e0def4
border-size=4
border-radius=0
progress-color=source #c4a7e7

width=450
height=250
margin=15,20
padding=15
max-icon-size=64

default-timeout=5000
ignore-timeout=1
max-visible=5

[urgency=normal]
border-color=#c4a7e7

[urgency=low]
border-color=#31748f

[urgency=high]
border-color=#eb6f92
background-color=#eb6f92
text-color=#191724
default-timeout=0
