# ~/.config/hypr/hyprlock.conf

general {
    hide_cursor = true
    disable_loading_bar = true
}

background {
    monitor =
    path = /home/christho/Immagini/wallhaven-exj2ek_2880x1800.png
    
    blur_passes = 3
    blur_size = 6
    noise = 0.03
    brightness = 0.35
}


shape {
    monitor =
    size = 740, 320              
    color = rgb(29, 32, 33)     
    border_size = 4               
    border_color = rgb(231, 138, 78) 
    rounding = 0                  
    
    position = 0, 190
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M:%S")</b>"
    color = rgb(221, 199, 161)    
    font_size = 100                
    font_family = IosevkaTerm Nerd Font Bold
    
    position = 0, 210
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "SYS.DATE: $(date +'%Y.%m.%d') // UNIX_TIME: $(date +'%s')"
    color = rgb(169, 182, 101)    
    font_size = 20
    font_family = IosevkaTerm Nerd Font Mono
    
    position = 0, 90
    halign = center
    valign = center
}


label {
    monitor =
    text = >_ TARGET_USER: $USER
    color = rgb(125, 174, 163)    
    font_size = 20
    font_family = IosevkaTerm Nerd Font Bold
    
    position = 0, -60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 450, 70
    outline_thickness = 4         
    rounding = 0                  
    
    outer_color = rgb(231, 138, 78) 
    inner_color = rgb(29, 32, 33)   
    font_color = rgb(221, 199, 161) 
    
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    
    fade_on_empty = false
    placeholder_text = <span font_family="IosevkaTerm Nerd Font Mono" foreground="##7c6f64">AWAITING_INPUT...</span>
    
    fail_text = <span font_family="IosevkaTerm Nerd Font Bold">AUTH_FAILED // ATTEMPT: $ATTEMPTS</span>
    fail_color = rgb(234, 105, 98)  
    
    position = 0, -130
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "BATTERY_LVL: $(cat /sys/class/power_supply/BAT0/capacity)% | SYS_UPTIME: $(uptime -p | sed 's/up //')"
    color = rgb(216, 166, 87)     
    font_size = 26
    font_family = IosevkaTerm Nerd Font Mono
    
    position = 0, 40
    halign = center
    valign = bottom
}
