# ~/.config/hypr/hypridle.conf

general {
    # Questo comando assicura che non si aprano 100 istanze di hyprlock per sbaglio
    lock_cmd = pidof hyprlock || hyprlock       
    
    # Se il pc va in sospensione forzata, blocca comunque lo schermo prima
    before_sleep_cmd = loginctl lock-session    
    
    # Riaccende i monitor quando il pc si sveglia dalla sospensione
    after_sleep_cmd = niri msg action power-on-monitors  
}

# 1. BLOCCO SCHERMO (A 2 minuti e 55 secondi)
listener {
    timeout = 175                                 # 175 secondi (2m e 55s)
    on-timeout = loginctl lock-session            # Attiva il lock_cmd (avvia hyprlock)
}

# 2. SPEGNIMENTO PIXEL OLED (A 3 minuti precisi)
listener {
    timeout = 180                                 # 180 secondi (3 minuti esatti)
    on-timeout = niri msg action power-off-monitors # Spegne fisicamente i display
    on-resume = niri msg action power-on-monitors   # Riaccende i display quando muovi il mouse
}
