# Hyprlock: stile CYBERPUNK (terminale neon, forme angolari)

general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(8, 8, 14)
}

# cornice neon
shape {
    monitor =
    size = 640, 380
    color = rgb(10, 10, 18)
    border_size = 2
    border_color = rgb(34, 211, 238)
    rounding = 0
    position = 0, 20
    halign = center
    valign = center
}

# tag magenta
shape {
    monitor =
    size = 240, 42
    color = rgb(255, 61, 154)
    border_size = 0
    rounding = 0
    position = 0, 150
    halign = center
    valign = center
}
label {
    monitor =
    text = ▚ SYSTEM LOCKED ▚
    color = rgb(10, 10, 18)
    font_size = 18
    font_family = IosevkaTerm Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}

# orologio neon verde
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M:%S"
    color = rgb(57, 255, 20)
    font_size = 82
    font_family = IosevkaTerm Nerd Font Bold
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgb(57, 255, 20)
    position = 0, 55
    halign = center
    valign = center
}

# riga terminale
label {
    monitor =
    text = root@arcichristho:~$ authenticate
    color = rgb(255, 61, 154)
    font_size = 15
    font_family = IosevkaTerm Nerd Font
    position = 0, -18
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 480, 50
    outline_thickness = 2
    rounding = 0
    outer_color = rgb(34, 211, 238)
    inner_color = rgb(12, 12, 20)
    font_color = rgb(57, 255, 20)
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    fade_on_empty = false
    placeholder_text = <span foreground="##39ff14">[ ENTER PASSCODE ]</span>
    fail_text = <span foreground="##ff3d9a">ACCESS DENIED — RETRY ($ATTEMPTS)</span>
    check_color = rgb(57, 255, 20)
    fail_color = rgb(255, 61, 154)
    position = 0, -120
    halign = center
    valign = center
}
